name: .NET Build & deploy Test Coverage with XPlat Code Coverage results to github pages on push and PR to main branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Run tests and collect coverage
        run: dotnet test --configuration Release --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults --logger "trx;LogFileName=TestResults.trx" --settings ./coverlet.runsettings

      - name: Upload code coverage results to GitHub Pages
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-results
          path: ./TestResults
      