name: .NET Build & Test Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./jonas.darts.backend

    - name: Build solution
      run: dotnet build --no-restore --configuration Release
      working-directory: ./jonas.darts.backend

    - name: Run tests with coverage
      run: dotnet test --no-build --configuration Release --collect:"XPlat Code Coverage"
      working-directory: ./jonas.darts.backend

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Generate coverage report
      run: |
        reportgenerator \
          -reports:"jonas.darts.backend/jonas.darts.backend/**/TestResults/**/coverage.cobertura.xml" \
          -targetdir:"coverage-report" \
          -reporttypes:Html

    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage-report
