name: .NET Build & Test Coverage

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore Jonas.Darts.Backend.sln
      working-directory: ./Jonas.Darts.Backend

    - name: Build solution
      run: dotnet build Jonas.Darts.Backend.sln --no-restore --configuration Release
      working-directory: ./Jonas.Darts.Backend

    - name: Run tests with coverage
      run: dotnet test Jonas.Darts.Backend.sln --no-build --configuration Release --collect:"XPlat Code Coverage"
      working-directory: ./Jonas.Darts.Backend

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Generate coverage report
      run: |
        reportgenerator \
          -reports:"./Jonas.Darts.Backend/**/TestResults/**/coverage.cobertura.xml" \
          -targetdir:"./Jonas.Darts.Backend/coverage-report" \
          -reporttypes:Html

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: coverage-report
        path: ./Jonas.Darts.Backend/coverage-report

  deploy-pages:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download coverage artifact
      uses: actions/download-artifact@v4
      with:
        name: coverage-report
        path: coverage-report

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./coverage-report
        publish_branch: gh-pages
